<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JpbAutoRoTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('jpb_auto_ro')->delete();
        
        \DB::table('jpb_auto_ro')->insert(array (
            0 => 
            array (
                'id' => 59,
                'id_member' => 22,
                'id_source' => 59,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-21 19:44:34',
            ),
            1 => 
            array (
                'id' => 119,
                'id_member' => 70,
                'id_source' => 119,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-21 19:57:53',
            ),
            2 => 
            array (
                'id' => 120,
                'id_member' => 22,
                'id_source' => 120,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-21 19:57:53',
            ),
            3 => 
            array (
                'id' => 182,
                'id_member' => 22,
                'id_source' => 182,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-21 20:12:53',
            ),
            4 => 
            array (
                'id' => 183,
                'id_member' => 21,
                'id_source' => 204,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-22 20:41:37',
            ),
            5 => 
            array (
                'id' => 184,
                'id_member' => 21,
                'id_source' => 227,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-22 20:43:42',
            ),
            6 => 
            array (
                'id' => 185,
                'id_member' => 21,
                'id_source' => 251,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-22 20:47:11',
            ),
            7 => 
            array (
                'id' => 186,
                'id_member' => 90,
                'id_source' => 274,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-22 20:52:28',
            ),
            8 => 
            array (
                'id' => 187,
                'id_member' => 21,
                'id_source' => 275,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-22 20:52:28',
            ),
            9 => 
            array (
                'id' => 188,
                'id_member' => 90,
                'id_source' => 300,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-22 20:55:29',
            ),
            10 => 
            array (
                'id' => 189,
                'id_member' => 21,
                'id_source' => 301,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-22 20:55:29',
            ),
            11 => 
            array (
                'id' => 190,
                'id_member' => 23,
                'id_source' => 329,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-23 21:00:21',
            ),
            12 => 
            array (
                'id' => 191,
                'id_member' => 167,
                'id_source' => 357,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-24 20:41:42',
            ),
            13 => 
            array (
                'id' => 192,
                'id_member' => 38,
                'id_source' => 385,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-25 15:15:05',
            ),
            14 => 
            array (
                'id' => 193,
                'id_member' => 178,
                'id_source' => 409,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-25 19:35:38',
            ),
            15 => 
            array (
                'id' => 194,
                'id_member' => 21,
                'id_source' => 410,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-25 19:35:38',
            ),
            16 => 
            array (
                'id' => 195,
                'id_member' => 10,
                'id_source' => 421,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-25 19:44:52',
            ),
            17 => 
            array (
                'id' => 196,
                'id_member' => 10,
                'id_source' => 433,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-25 19:46:44',
            ),
            18 => 
            array (
                'id' => 197,
                'id_member' => 10,
                'id_source' => 446,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-25 19:48:10',
            ),
            19 => 
            array (
                'id' => 198,
                'id_member' => 13,
                'id_source' => 459,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-25 20:19:24',
            ),
            20 => 
            array (
                'id' => 199,
                'id_member' => 10,
                'id_source' => 460,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-25 20:19:24',
            ),
            21 => 
            array (
                'id' => 200,
                'id_member' => 9,
                'id_source' => 481,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-27 12:27:29',
            ),
            22 => 
            array (
                'id' => 201,
                'id_member' => 21,
                'id_source' => 506,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-29 16:58:43',
            ),
            23 => 
            array (
                'id' => 202,
                'id_member' => 21,
                'id_source' => 533,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-04-29 17:08:02',
            ),
            24 => 
            array (
                'id' => 203,
                'id_member' => 28,
                'id_source' => 567,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-01 14:28:55',
            ),
            25 => 
            array (
                'id' => 204,
                'id_member' => 23,
                'id_source' => 568,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-01 14:28:55',
            ),
            26 => 
            array (
                'id' => 205,
                'id_member' => 55,
                'id_source' => 590,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-01 20:27:05',
            ),
            27 => 
            array (
                'id' => 206,
                'id_member' => 21,
                'id_source' => 591,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-01 20:27:05',
            ),
            28 => 
            array (
                'id' => 207,
                'id_member' => 55,
                'id_source' => 615,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-01 20:30:37',
            ),
            29 => 
            array (
                'id' => 208,
                'id_member' => 21,
                'id_source' => 616,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-01 20:30:37',
            ),
            30 => 
            array (
                'id' => 209,
                'id_member' => 55,
                'id_source' => 642,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-01 21:40:56',
            ),
            31 => 
            array (
                'id' => 210,
                'id_member' => 221,
                'id_source' => 669,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-02 11:48:45',
            ),
            32 => 
            array (
                'id' => 211,
                'id_member' => 39,
                'id_source' => 695,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-04 20:41:30',
            ),
            33 => 
            array (
                'id' => 212,
                'id_member' => 21,
                'id_source' => 696,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-04 20:41:30',
            ),
            34 => 
            array (
                'id' => 213,
                'id_member' => 15,
                'id_source' => 709,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-05 17:38:42',
            ),
            35 => 
            array (
                'id' => 214,
                'id_member' => 9,
                'id_source' => 710,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-05 17:38:42',
            ),
            36 => 
            array (
                'id' => 215,
                'id_member' => 209,
                'id_source' => 725,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-05 18:09:41',
            ),
            37 => 
            array (
                'id' => 216,
                'id_member' => 13,
                'id_source' => 726,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-05 18:09:41',
            ),
            38 => 
            array (
                'id' => 217,
                'id_member' => 10,
                'id_source' => 727,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-05 18:09:41',
            ),
            39 => 
            array (
                'id' => 218,
                'id_member' => 55,
                'id_source' => 755,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-06 23:48:16',
            ),
            40 => 
            array (
                'id' => 219,
                'id_member' => 21,
                'id_source' => 784,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-07 21:07:57',
            ),
            41 => 
            array (
                'id' => 220,
                'id_member' => 26,
                'id_source' => 814,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-15 19:08:41',
            ),
            42 => 
            array (
                'id' => 221,
                'id_member' => 23,
                'id_source' => 815,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-15 19:08:41',
            ),
            43 => 
            array (
                'id' => 222,
                'id_member' => 21,
                'id_source' => 816,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-15 19:08:41',
            ),
            44 => 
            array (
                'id' => 223,
                'id_member' => 56,
                'id_source' => 844,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-16 09:59:48',
            ),
            45 => 
            array (
                'id' => 224,
                'id_member' => 38,
                'id_source' => 845,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-16 09:59:48',
            ),
            46 => 
            array (
                'id' => 225,
                'id_member' => 167,
                'id_source' => 874,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-18 13:27:17',
            ),
            47 => 
            array (
                'id' => 226,
                'id_member' => 41,
                'id_source' => 900,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-20 16:03:19',
            ),
            48 => 
            array (
                'id' => 227,
                'id_member' => 38,
                'id_source' => 901,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-20 16:03:19',
            ),
            49 => 
            array (
                'id' => 228,
                'id_member' => 90,
                'id_source' => 927,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-24 21:20:19',
            ),
            50 => 
            array (
                'id' => 229,
                'id_member' => 21,
                'id_source' => 928,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-24 21:20:19',
            ),
            51 => 
            array (
                'id' => 230,
                'id_member' => 38,
                'id_source' => 957,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-27 22:05:15',
            ),
            52 => 
            array (
                'id' => 231,
                'id_member' => 36,
                'id_source' => 991,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-29 12:57:37',
            ),
            53 => 
            array (
                'id' => 232,
                'id_member' => 26,
                'id_source' => 992,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-29 12:57:37',
            ),
            54 => 
            array (
                'id' => 233,
                'id_member' => 23,
                'id_source' => 993,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-29 12:57:37',
            ),
            55 => 
            array (
                'id' => 234,
                'id_member' => 23,
                'id_source' => 1022,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-29 19:49:19',
            ),
            56 => 
            array (
                'id' => 235,
                'id_member' => 171,
                'id_source' => 1053,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-05-30 21:59:43',
            ),
            57 => 
            array (
                'id' => 236,
                'id_member' => 21,
                'id_source' => 1080,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-03 23:12:32',
            ),
            58 => 
            array (
                'id' => 237,
                'id_member' => 106,
                'id_source' => 1098,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-04 12:36:35',
            ),
            59 => 
            array (
                'id' => 238,
                'id_member' => 9,
                'id_source' => 1099,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-04 12:36:35',
            ),
            60 => 
            array (
                'id' => 239,
                'id_member' => 17,
                'id_source' => 1116,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-04 16:55:46',
            ),
            61 => 
            array (
                'id' => 240,
                'id_member' => 17,
                'id_source' => 1134,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-04 16:57:58',
            ),
            62 => 
            array (
                'id' => 241,
                'id_member' => 237,
                'id_source' => 1151,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-04 17:00:09',
            ),
            63 => 
            array (
                'id' => 242,
                'id_member' => 17,
                'id_source' => 1152,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-04 17:00:09',
            ),
            64 => 
            array (
                'id' => 243,
                'id_member' => 237,
                'id_source' => 1170,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-04 17:04:05',
            ),
            65 => 
            array (
                'id' => 244,
                'id_member' => 17,
                'id_source' => 1171,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-04 17:04:05',
            ),
            66 => 
            array (
                'id' => 245,
                'id_member' => 11,
                'id_source' => 1190,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-07 11:54:27',
            ),
            67 => 
            array (
                'id' => 246,
                'id_member' => 9,
                'id_source' => 1191,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-07 11:54:27',
            ),
            68 => 
            array (
                'id' => 247,
                'id_member' => 109,
                'id_source' => 1211,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 14:05:36',
            ),
            69 => 
            array (
                'id' => 248,
                'id_member' => 9,
                'id_source' => 1212,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 14:05:36',
            ),
            70 => 
            array (
                'id' => 249,
                'id_member' => 108,
                'id_source' => 1225,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 14:44:44',
            ),
            71 => 
            array (
                'id' => 250,
                'id_member' => 106,
                'id_source' => 1226,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 14:44:44',
            ),
            72 => 
            array (
                'id' => 251,
                'id_member' => 9,
                'id_source' => 1227,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 14:44:44',
            ),
            73 => 
            array (
                'id' => 252,
                'id_member' => 9,
                'id_source' => 1241,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 14:48:06',
            ),
            74 => 
            array (
                'id' => 253,
                'id_member' => 9,
                'id_source' => 1257,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 14:57:48',
            ),
            75 => 
            array (
                'id' => 254,
                'id_member' => 9,
                'id_source' => 1273,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 16:04:53',
            ),
            76 => 
            array (
                'id' => 255,
                'id_member' => 258,
                'id_source' => 1289,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 16:06:56',
            ),
            77 => 
            array (
                'id' => 256,
                'id_member' => 9,
                'id_source' => 1290,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 16:06:56',
            ),
            78 => 
            array (
                'id' => 257,
                'id_member' => 39,
                'id_source' => 1317,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-11 19:34:21',
            ),
            79 => 
            array (
                'id' => 258,
                'id_member' => 42,
                'id_source' => 1347,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-12 20:40:12',
            ),
            80 => 
            array (
                'id' => 259,
                'id_member' => 22,
                'id_source' => 1348,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-12 20:40:12',
            ),
            81 => 
            array (
                'id' => 260,
                'id_member' => 17,
                'id_source' => 1367,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-13 16:07:35',
            ),
            82 => 
            array (
                'id' => 261,
                'id_member' => 38,
                'id_source' => 1396,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-18 23:42:14',
            ),
            83 => 
            array (
                'id' => 262,
                'id_member' => 39,
                'id_source' => 1424,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-20 22:15:29',
            ),
            84 => 
            array (
                'id' => 263,
                'id_member' => 90,
                'id_source' => 1450,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-22 15:21:07',
            ),
            85 => 
            array (
                'id' => 264,
                'id_member' => 21,
                'id_source' => 1451,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-22 15:21:07',
            ),
            86 => 
            array (
                'id' => 265,
                'id_member' => 258,
                'id_source' => 1468,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-26 12:56:22',
            ),
            87 => 
            array (
                'id' => 266,
                'id_member' => 9,
                'id_source' => 1469,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-26 12:56:22',
            ),
            88 => 
            array (
                'id' => 267,
                'id_member' => 9,
                'id_source' => 1487,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-26 12:58:02',
            ),
            89 => 
            array (
                'id' => 268,
                'id_member' => 262,
                'id_source' => 1515,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-26 21:01:06',
            ),
            90 => 
            array (
                'id' => 269,
                'id_member' => 39,
                'id_source' => 1516,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-06-26 21:01:06',
            ),
            91 => 
            array (
                'id' => 270,
                'id_member' => 24,
                'id_source' => 1541,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-07-10 21:04:06',
            ),
            92 => 
            array (
                'id' => 271,
                'id_member' => 23,
                'id_source' => 1542,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-07-10 21:04:06',
            ),
            93 => 
            array (
                'id' => 272,
                'id_member' => 237,
                'id_source' => 1561,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-07-15 10:26:03',
            ),
            94 => 
            array (
                'id' => 273,
                'id_member' => 17,
                'id_source' => 1562,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-07-15 10:26:03',
            ),
            95 => 
            array (
                'id' => 274,
                'id_member' => 274,
                'id_source' => 1569,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-07-21 23:25:18',
            ),
            96 => 
            array (
                'id' => 275,
                'id_member' => 17,
                'id_source' => 1589,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-08-15 11:55:31',
            ),
            97 => 
            array (
                'id' => 276,
                'id_member' => 237,
                'id_source' => 1609,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-08-15 11:58:56',
            ),
            98 => 
            array (
                'id' => 277,
                'id_member' => 17,
                'id_source' => 1610,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-08-15 11:58:56',
            ),
            99 => 
            array (
                'id' => 278,
                'id_member' => 57,
                'id_source' => 1637,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-08-22 14:41:54',
            ),
            100 => 
            array (
                'id' => 279,
                'id_member' => 56,
                'id_source' => 1638,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-08-22 14:41:54',
            ),
            101 => 
            array (
                'id' => 280,
                'id_member' => 38,
                'id_source' => 1639,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-08-22 14:41:54',
            ),
            102 => 
            array (
                'id' => 281,
                'id_member' => 46,
                'id_source' => 1665,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-09-01 14:25:38',
            ),
            103 => 
            array (
                'id' => 282,
                'id_member' => 42,
                'id_source' => 1666,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-09-01 14:25:38',
            ),
            104 => 
            array (
                'id' => 283,
                'id_member' => 22,
                'id_source' => 1667,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-09-01 14:25:38',
            ),
            105 => 
            array (
                'id' => 284,
                'id_member' => 44,
                'id_source' => 1692,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-09-01 14:41:05',
            ),
            106 => 
            array (
                'id' => 285,
                'id_member' => 42,
                'id_source' => 1693,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-09-01 14:41:05',
            ),
            107 => 
            array (
                'id' => 286,
                'id_member' => 22,
                'id_source' => 1694,
                'source' => 'bonus',
                'nominal' => 146250.0,
                'percent' => 20,
                'amount' => 29250.0,
                'status' => 1,
            'description' => 'Bonus Pairing (2.500 BV)',
                'datecreated' => '2025-09-01 14:41:05',
            ),
        ));
        
        
    }
}