<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JpbBanksTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('jpb_banks')->delete();

        \DB::table('jpb_banks')->insert([
            0 => [
                'id' => 1,
                'nama' => 'BCA',
                'kode' => '014',
                'type' => 'bank',
                'flipcode' => 'bca',
                'espaycode' => '014',
                'linkitacode' => '014',
                'logo' => 'dhaassets/backend/img/bank/bca.png',
            ],
            1 => [
                'id' => 2,
                'nama' => 'BNI',
                'kode' => '009',
                'type' => 'bank',
                'flipcode' => 'bni',
                'espaycode' => '009',
                'linkitacode' => '009',
                'logo' => 'dhaassets/backend/img/bank/bni.png',
            ],
            2 => [
                'id' => 3,
                'nama' => 'BRI',
                'kode' => '002',
                'type' => 'bank',
                'flipcode' => 'bri',
                'espaycode' => '002',
                'linkitacode' => '002',
                'logo' => 'dhaassets/backend/img/bank/briva.png',
            ],
            3 => [
                'id' => 4,
                'nama' => 'Mandiri',
                'kode' => '008',
                'type' => 'bank',
                'flipcode' => 'mandiri',
                'espaycode' => '008',
                'linkitacode' => '008',
                'logo' => 'dhaassets/backend/img/bank/mandiri.png',
            ],
            4 => [
                'id' => 5,
                'nama' => 'BSI',
                'kode' => '451',
                'type' => 'bank',
                'flipcode' => 'bsm',
                'espaycode' => null,
                'linkitacode' => '451',
                'logo' => null,
            ],
            5 => [
                'id' => 6,
                'nama' => 'CIMB Niaga',
                'kode' => '022',
                'type' => 'bank',
                'flipcode' => 'cimb',
                'espaycode' => '022',
                'linkitacode' => '022',
                'logo' => 'dhaassets/backend/img/bank/cimb.png',
            ],
            6 => [
                'id' => 7,
                'nama' => 'CIMB Niaga Syariah',
                'kode' => '022',
                'type' => 'bank',
                'flipcode' => 'cimb',
                'espaycode' => null,
                'linkitacode' => '022',
                'logo' => null,
            ],
            7 => [
                'id' => 8,
                'nama' => 'Muamalat',
                'kode' => '147',
                'type' => 'bank',
                'flipcode' => 'muamalat',
                'espaycode' => null,
                'linkitacode' => '147',
                'logo' => null,
            ],
            8 => [
                'id' => 9,
                'nama' => 'BRI Syariah',
                'kode' => '422',
                'type' => 'bank',
                'flipcode' => 'bri_syr',
                'espaycode' => null,
                'linkitacode' => '422',
                'logo' => null,
            ],
            9 => [
                'id' => 10,
                'nama' => 'BTN',
                'kode' => '200',
                'type' => 'bank',
                'flipcode' => 'btn',
                'espaycode' => null,
                'linkitacode' => '200',
                'logo' => null,
            ],
            10 => [
                'id' => 11,
                'nama' => 'Permata Bank',
                'kode' => '013',
                'type' => 'bank',
                'flipcode' => 'permata',
                'espaycode' => '013',
                'linkitacode' => '013',
                'logo' => 'dhaassets/backend/img/bank/permata.png',
            ],
            11 => [
                'id' => 12,
                'nama' => 'Danamon',
                'kode' => '011',
                'type' => 'bank',
                'flipcode' => 'danamon',
                'espaycode' => null,
                'linkitacode' => '011',
                'logo' => null,
            ],
            12 => [
                'id' => 13,
                'nama' => 'BII Maybank',
                'kode' => '016',
                'type' => 'bank',
                'flipcode' => 'bii',
                'espaycode' => null,
                'linkitacode' => '016',
                'logo' => null,
            ],
            13 => [
                'id' => 14,
                'nama' => 'Mega',
                'kode' => '426',
                'type' => 'bank',
                'flipcode' => 'mega',
                'espaycode' => null,
                'linkitacode' => '426',
                'logo' => null,
            ],
            14 => [
                'id' => 15,
                'nama' => 'Sinarmas',
                'kode' => '153',
                'type' => 'bank',
                'flipcode' => 'sinarmas',
                'espaycode' => null,
                'linkitacode' => '153',
                'logo' => null,
            ],
            15 => [
                'id' => 16,
                'nama' => 'OCBC NISP',
                'kode' => '028',
                'type' => 'bank',
                'flipcode' => 'ocbc',
                'espaycode' => null,
                'linkitacode' => '028',
                'logo' => null,
            ],
            16 => [
                'id' => 17,
                'nama' => 'Bukopin',
                'kode' => '441',
                'type' => 'bank',
                'flipcode' => 'bukopin',
                'espaycode' => null,
                'linkitacode' => '441',
                'logo' => null,
            ],
            17 => [
                'id' => 18,
                'nama' => 'BCA Syariah',
                'kode' => '536',
                'type' => 'bank',
                'flipcode' => 'bca_syr',
                'espaycode' => null,
                'linkitacode' => '536',
                'logo' => null,
            ],
            18 => [
                'id' => 19,
                'nama' => 'Lippo',
                'kode' => '026',
                'type' => 'bank',
                'flipcode' => '',
                'espaycode' => null,
                'linkitacode' => '026',
                'logo' => null,
            ],
            19 => [
                'id' => 20,
                'nama' => 'Citibank',
                'kode' => '031',
                'type' => 'bank',
                'flipcode' => 'citibank',
                'espaycode' => null,
                'linkitacode' => '031',
                'logo' => null,
            ],
            20 => [
                'id' => 21,
                'nama' => 'BTPN',
                'kode' => '213',
                'type' => 'bank',
                'flipcode' => 'tabungan_pensiunan_nasional',
                'espaycode' => null,
                'linkitacode' => '213',
                'logo' => null,
            ],
            21 => [
                'id' => 22,
                'nama' => 'BPD Jabar Banten (BJB)',
                'kode' => '110',
                'type' => 'bank',
                'flipcode' => 'bjb',
                'espaycode' => null,
                'linkitacode' => '110',
                'logo' => null,
            ],
            22 => [
                'id' => 23,
                'nama' => 'Bank DKI',
                'kode' => '111',
                'type' => 'bank',
                'flipcode' => 'dki',
                'espaycode' => null,
                'linkitacode' => '111',
                'logo' => null,
            ],
            23 => [
                'id' => 24,
                'nama' => 'BPD DIY',
                'kode' => '112',
                'type' => 'bank',
                'flipcode' => 'daerah_istimewa',
                'espaycode' => null,
                'linkitacode' => '112',
                'logo' => null,
            ],
            24 => [
                'id' => 25,
                'nama' => 'BPD Jateng',
                'kode' => '113',
                'type' => 'bank',
                'flipcode' => 'jawa_tengah',
                'espaycode' => null,
                'linkitacode' => '113',
                'logo' => null,
            ],
            25 => [
                'id' => 26,
                'nama' => 'BPD Jatim',
                'kode' => '114',
                'type' => 'bank',
                'flipcode' => 'jawa_timur',
                'espaycode' => null,
                'linkitacode' => '114',
                'logo' => null,
            ],
            26 => [
                'id' => 27,
                'nama' => 'BPD Jambi',
                'kode' => '115',
                'type' => 'bank',
                'flipcode' => 'jambi',
                'espaycode' => null,
                'linkitacode' => '115',
                'logo' => null,
            ],
            27 => [
                'id' => 28,
                'nama' => 'BPD Aceh',
                'kode' => '116',
                'type' => 'bank',
                'flipcode' => '',
                'espaycode' => null,
                'linkitacode' => '116',
                'logo' => null,
            ],
            28 => [
                'id' => 29,
                'nama' => 'BPD Sumut',
                'kode' => '117',
                'type' => 'bank',
                'flipcode' => 'sumut',
                'espaycode' => null,
                'linkitacode' => '117',
                'logo' => null,
            ],
            29 => [
                'id' => 30,
                'nama' => 'Bank Nagari (BPD Sumbar)',
                'kode' => '118',
                'type' => 'bank',
                'flipcode' => 'sumatera_barat',
                'espaycode' => null,
                'linkitacode' => '118',
                'logo' => null,
            ],
            30 => [
                'id' => 31,
                'nama' => 'BPD Riau Kepri',
                'kode' => '119',
                'type' => 'bank',
                'flipcode' => 'riau_dan_kepri',
                'espaycode' => null,
                'linkitacode' => '119',
                'logo' => null,
            ],
            31 => [
                'id' => 32,
                'nama' => 'BPD Sumsel Babel',
                'kode' => '120',
                'type' => 'bank',
                'flipcode' => 'sumsel_dan_babel',
                'espaycode' => null,
                'linkitacode' => '120',
                'logo' => null,
            ],
            32 => [
                'id' => 33,
                'nama' => 'BPD Lampung',
                'kode' => '121',
                'type' => 'bank',
                'flipcode' => 'lampung',
                'espaycode' => null,
                'linkitacode' => '121',
                'logo' => null,
            ],
            33 => [
                'id' => 34,
                'nama' => 'BPD Kalsel',
                'kode' => '122',
                'type' => 'bank',
                'flipcode' => 'kalimantan_selatan',
                'espaycode' => null,
                'linkitacode' => '122',
                'logo' => null,
            ],
            34 => [
                'id' => 35,
                'nama' => 'BPD Kalimantan Barat',
                'kode' => '123',
                'type' => 'bank',
                'flipcode' => 'kalimantan_barat',
                'espaycode' => null,
                'linkitacode' => '123',
                'logo' => null,
            ],
            35 => [
                'id' => 36,
                'nama' => 'BPD Kaltim',
                'kode' => '124',
                'type' => 'bank',
                'flipcode' => 'kalimantan_timur',
                'espaycode' => null,
                'linkitacode' => '124',
                'logo' => null,
            ],
            36 => [
                'id' => 37,
                'nama' => 'BPD Kalteng',
                'kode' => '125',
                'type' => 'bank',
                'flipcode' => 'kalimantan_tengah',
                'espaycode' => null,
                'linkitacode' => '125',
                'logo' => null,
            ],
            37 => [
                'id' => 38,
                'nama' => 'BPD Sulselbar',
                'kode' => '126',
                'type' => 'bank',
                'flipcode' => 'sulselbar',
                'espaycode' => null,
                'linkitacode' => '126',
                'logo' => null,
            ],
            38 => [
                'id' => 39,
                'nama' => 'Bank Sulut',
                'kode' => '127',
                'type' => 'bank',
                'flipcode' => 'sulut',
                'espaycode' => null,
                'linkitacode' => '127',
                'logo' => null,
            ],
            39 => [
                'id' => 40,
                'nama' => 'BPD NTB',
                'kode' => '128',
                'type' => 'bank',
                'flipcode' => 'nusa_tenggara_barat',
                'espaycode' => null,
                'linkitacode' => '128',
                'logo' => null,
            ],
            40 => [
                'id' => 41,
                'nama' => 'BPD Bali',
                'kode' => '129',
                'type' => 'bank',
                'flipcode' => 'bali',
                'espaycode' => null,
                'linkitacode' => '129',
                'logo' => null,
            ],
            41 => [
                'id' => 42,
                'nama' => 'BPD NTT',
                'kode' => '130',
                'type' => 'bank',
                'flipcode' => 'nusa_tenggara_timur',
                'espaycode' => null,
                'linkitacode' => '130',
                'logo' => null,
            ],
            42 => [
                'id' => 43,
                'nama' => 'BPD Maluku',
                'kode' => '131',
                'type' => 'bank',
                'flipcode' => 'maluku',
                'espaycode' => null,
                'linkitacode' => '131',
                'logo' => null,
            ],
            43 => [
                'id' => 44,
                'nama' => 'BPD Papua',
                'kode' => '132',
                'type' => 'bank',
                'flipcode' => 'papua',
                'espaycode' => null,
                'linkitacode' => '132',
                'logo' => null,
            ],
            44 => [
                'id' => 45,
                'nama' => 'BPD Bengkulu',
                'kode' => '133',
                'type' => 'bank',
                'flipcode' => 'bengkulu',
                'espaycode' => null,
                'linkitacode' => '133',
                'logo' => null,
            ],
            45 => [
                'id' => 46,
                'nama' => 'BPD Sulawesi Tengah',
                'kode' => '134',
                'type' => 'bank',
                'flipcode' => 'sulawesi',
                'espaycode' => null,
                'linkitacode' => '134',
                'logo' => null,
            ],
            46 => [
                'id' => 47,
                'nama' => 'BPD Sultra',
                'kode' => '135',
                'type' => 'bank',
                'flipcode' => 'sulawesi_tenggara',
                'espaycode' => null,
                'linkitacode' => '135',
                'logo' => null,
            ],
            47 => [
                'id' => 48,
                'nama' => 'Panin Bank',
                'kode' => '019',
                'type' => 'bank',
                'flipcode' => 'panin',
                'espaycode' => null,
                'linkitacode' => '019',
                'logo' => null,
            ],
            48 => [
                'id' => 49,
                'nama' => 'DBS Indonesia',
                'kode' => '046',
                'type' => 'bank',
                'flipcode' => 'dbs',
                'espaycode' => null,
                'linkitacode' => '046',
                'logo' => null,
            ],
            49 => [
                'id' => 50,
                'nama' => 'Bank Victoria',
                'kode' => '566',
                'type' => 'bank',
                'flipcode' => 'victoria_internasional',
                'espaycode' => null,
                'linkitacode' => '566',
                'logo' => null,
            ],
            50 => [
                'id' => 51,
                'nama' => 'Bank BJB Syariah',
                'kode' => '425',
                'type' => 'bank',
                'flipcode' => 'bjb_syr',
                'espaycode' => null,
                'linkitacode' => '425',
                'logo' => null,
            ],
            51 => [
                'id' => 52,
                'nama' => 'BNI Syariah',
                'kode' => '427',
                'type' => 'bank',
                'flipcode' => 'bni',
                'espaycode' => null,
                'linkitacode' => '427',
                'logo' => null,
            ],
            52 => [
                'id' => 53,
                'nama' => 'Bank National Nobu (BANK ALFINDO)',
                'kode' => '503',
                'type' => 'bank',
                'flipcode' => 'nationalnobu',
                'espaycode' => null,
                'linkitacode' => '503',
                'logo' => null,
            ],
            53 => [
                'id' => 54,
                'nama' => 'Artha Graha International',
                'kode' => '037',
                'type' => 'bank',
                'flipcode' => 'artha',
                'espaycode' => null,
                'linkitacode' => '037',
                'logo' => null,
            ],
            54 => [
                'id' => 55,
                'nama' => 'SeaBank (BKE)',
                'kode' => '535',
                'type' => 'bank',
                'flipcode' => 'kesejahteraan_ekonomi',
                'espaycode' => null,
                'linkitacode' => '535',
                'logo' => null,
            ],
            55 => [
                'id' => 56,
                'nama' => 'DANA',
                'kode' => '991',
                'type' => 'emoney',
                'flipcode' => 'dana',
                'espaycode' => null,
                'linkitacode' => 'dana',
                'logo' => null,
            ],
            56 => [
                'id' => 57,
                'nama' => 'OVO',
                'kode' => '992',
                'type' => 'emoney',
                'flipcode' => 'ovo',
                'espaycode' => null,
                'linkitacode' => 'ovo',
                'logo' => null,
            ],
            57 => [
                'id' => 58,
                'nama' => 'GOPAY',
                'kode' => '993',
                'type' => 'emoney',
                'flipcode' => 'gopay',
                'espaycode' => null,
                'linkitacode' => 'gopay',
                'logo' => null,
            ],
            58 => [
                'id' => 59,
                'nama' => 'Bank Jago Syariah',
                'kode' => '542',
                'type' => 'bank',
                'flipcode' => 'artos_syr',
                'espaycode' => null,
                'linkitacode' => '542',
                'logo' => null,
            ],
        ]);

    }
}
