<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JpbCartTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('jpb_cart')->delete();
        
        \DB::table('jpb_cart')->insert(array (
            0 => 
            array (
                'id' => 'anBxQ0ZKaWFFZTdvd1hTSHQxWlg1QT09',
                'cart_code' => 'SFJzOGd0U0wyZUJGaFlNcXUwQ0JMdz09',
                'id_member' => 166,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 1,
                'product_id' => 1,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'B4 Formats',
                'weight' => 1.0,
                'bv' => 0.0,
                'price' => 3300000.0,
                'qty' => 3,
                'subtotal' => 9900000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-04-21 12:57:28',
                'datemodified' => '2025-04-21 12:57:33',
            ),
            1 => 
            array (
                'id' => 'bUloMDJneHBZVjR6VUJVYkh3WGt4QT09',
                'cart_code' => 'VGk1V1ZIUW50QUttMFhqM2FML3VCdz09',
                'id_member' => 2,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 1,
                'product_id' => 1,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'B4 Formats',
                'weight' => 1.0,
                'bv' => 2500.0,
                'price' => 3300000.0,
                'qty' => 4,
                'subtotal' => 13200000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-05-05 11:05:12',
                'datemodified' => '2025-07-25 08:58:16',
            ),
            2 => 
            array (
                'id' => 'MkNXQ1grZUpkNklDV2MyMDVZYWxJZz09',
                'cart_code' => 'cm16ZjlyK0lORk96YU13cWplUTFCUT09',
                'id_member' => 23,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 4,
                'product_id' => 4,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'Minicon M24',
                'weight' => 0.0,
                'bv' => 0.0,
                'price' => 0.0,
                'qty' => 0,
                'subtotal' => 0.0,
                'total_item' => 0,
                'items' => '',
                'status' => 0,
                'datecreated' => '2025-07-23 23:27:40',
                'datemodified' => '2025-07-30 04:21:02',
            ),
            3 => 
            array (
                'id' => 'NlZWRVVTYXBEZWhHbmxYeGNQOG1BUT09',
                'cart_code' => 'azUwakxac1hBQ24zQ1llTDZnWEZiZz09',
                'id_member' => 2,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 3,
                'product_id' => 3,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'Minicon M12',
                'weight' => 2000.0,
                'bv' => 2500.0,
                'price' => 3300000.0,
                'qty' => 1,
                'subtotal' => 3300000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-07-24 07:51:51',
                'datemodified' => '2025-07-25 09:01:05',
            ),
            4 => 
            array (
                'id' => 'Nnk3S0NKOElNOUhtWVRhbzZyTXhBUT09',
                'cart_code' => 'TFVpZGRoMllKRXMzMjVMSWdVNWozUT09',
                'id_member' => 81,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 2,
                'product_id' => 2,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'Paket B',
                'weight' => 1000.0,
                'bv' => 0.0,
                'price' => 6500000.0,
                'qty' => 1,
                'subtotal' => 6500000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-04-18 20:12:14',
                'datemodified' => NULL,
            ),
            5 => 
            array (
                'id' => 'RFVXOGZTOVNaSGxJbDB6QjhrQmRZUT09',
                'cart_code' => 'WUd0cGROVVczQWRlT0RMbEZqQ0FYZz09',
                'id_member' => 8,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 1,
                'product_id' => 1,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'B4 Formats',
                'weight' => 1.0,
                'bv' => 2500.0,
                'price' => 3300000.0,
                'qty' => 1,
                'subtotal' => 3300000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-07-21 17:55:56',
                'datemodified' => '2025-07-21 18:21:34',
            ),
            6 => 
            array (
                'id' => 'SmI0NnR1NEZ4TTJsN1hCVUZnaFZUUT09',
                'cart_code' => 'YjVGTlpwMjBvYUFEZWJaU3Uvd291dz09',
                'id_member' => 274,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 3,
                'product_id' => 3,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'Minicon M12',
                'weight' => 2000.0,
                'bv' => 2500.0,
                'price' => 3300000.0,
                'qty' => 1,
                'subtotal' => 3300000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-07-24 19:40:29',
                'datemodified' => '2025-09-03 12:46:09',
            ),
            7 => 
            array (
                'id' => 'TU1VdWJGaXZETGxjd3djdTBrc3ZCZz09',
                'cart_code' => 'RHFTQ28xNElYeFhzMk9HY3JiS0xmQT09',
                'id_member' => 23,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 3,
                'product_id' => 3,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'Minicon M12',
                'weight' => 0.0,
                'bv' => 0.0,
                'price' => 0.0,
                'qty' => 0,
                'subtotal' => 0.0,
                'total_item' => 0,
                'items' => '',
                'status' => 0,
                'datecreated' => '2025-07-30 04:20:41',
                'datemodified' => '2025-07-30 04:21:06',
            ),
            8 => 
            array (
                'id' => 'UGxBWWsyMDBoM3ppNzlyZDRHRzM5dz09',
                'cart_code' => 'WTRvUWxMOW9kSUtrUHVpTFpCdndIQT09',
                'id_member' => 206,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 1,
                'product_id' => 1,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'B4 Formats',
                'weight' => 1.0,
                'bv' => 2500.0,
                'price' => 3300000.0,
                'qty' => 1,
                'subtotal' => 3300000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-07-07 18:12:25',
                'datemodified' => NULL,
            ),
            9 => 
            array (
                'id' => 'Y3Bqa1hNZ1B5TkdFZTZuc1dLWUZPQT09',
                'cart_code' => 'NmNBZFltQTV1cU91cnlkUWFlbXBJZz09',
                'id_member' => 274,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 1,
                'product_id' => 1,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'B4 Formats',
                'weight' => 1.0,
                'bv' => 2500.0,
                'price' => 3300000.0,
                'qty' => 4,
                'subtotal' => 13200000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-07-24 08:46:42',
                'datemodified' => '2025-09-03 12:46:10',
            ),
            10 => 
            array (
                'id' => 'YjJ4RGJGdWRXcktQRnRpMU1IUWpYQT09',
                'cart_code' => 'Z1JNU2h5d2VIRGJIV2FacUFRZllHZz09',
                'id_member' => 23,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 1,
                'product_id' => 1,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'B4 Formats',
                'weight' => 0.0,
                'bv' => 0.0,
                'price' => 0.0,
                'qty' => 0,
                'subtotal' => 0.0,
                'total_item' => 0,
                'items' => '',
                'status' => 0,
                'datecreated' => '2025-06-16 10:44:55',
                'datemodified' => '2025-07-30 04:21:04',
            ),
            11 => 
            array (
                'id' => 'ZVZwWHMzWHJFb1VZbGQ4Q3MwSjd0dz09',
                'cart_code' => 'UTNuSmtGTTU0Y3dwakdzVkdQNnZqZz09',
                'id_member' => 237,
                'type' => 'shop_order',
                'grouping' => 'product',
                'grouping_id' => 1,
                'product_id' => 1,
                'package_id' => 0,
                'varian_id' => 0,
                'name' => 'B4 Formats',
                'weight' => 1.0,
                'bv' => 2500.0,
                'price' => 3300000.0,
                'qty' => 1,
                'subtotal' => 3300000.0,
                'total_item' => 1,
                'items' => '',
                'status' => 1,
                'datecreated' => '2025-06-11 04:46:56',
                'datemodified' => NULL,
            ),
        ));
        
        
    }
}