<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JpbMemberPointTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('jpb_member_point')->delete();
        
        \DB::table('jpb_member_point')->insert(array (
            0 => 
            array (
                'id' => 1,
                'id_member' => 39,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 17500.0,
                'point_right' => 10000.0,
                'point_qualified' => 10000.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-08-22 14:35:18',
            ),
            1 => 
            array (
                'id' => 2,
                'id_member' => 38,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 27500.0,
                'point_right' => 15000.0,
                'point_qualified' => 15000.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:33:27',
            ),
            2 => 
            array (
                'id' => 3,
                'id_member' => 23,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 15000.0,
                'point_right' => 42500.0,
                'point_qualified' => 15000.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:33:27',
            ),
            3 => 
            array (
                'id' => 4,
                'id_member' => 22,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 57500.0,
                'point_right' => 15000.0,
                'point_qualified' => 15000.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            4 => 
            array (
                'id' => 5,
                'id_member' => 21,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 72500.0,
                'point_right' => 40000.0,
                'point_qualified' => 40000.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            5 => 
            array (
                'id' => 6,
                'id_member' => 20,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 112500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            6 => 
            array (
                'id' => 7,
                'id_member' => 18,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 112500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            7 => 
            array (
                'id' => 8,
                'id_member' => 17,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 112500.0,
                'point_right' => 20000.0,
                'point_qualified' => 20000.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            8 => 
            array (
                'id' => 9,
                'id_member' => 16,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 132500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            9 => 
            array (
                'id' => 10,
                'id_member' => 12,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 132500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            10 => 
            array (
                'id' => 11,
                'id_member' => 10,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 132500.0,
                'point_right' => 12500.0,
                'point_qualified' => 12500.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            11 => 
            array (
                'id' => 12,
                'id_member' => 9,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 145000.0,
                'point_right' => 30000.0,
                'point_qualified' => 30000.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            12 => 
            array (
                'id' => 13,
                'id_member' => 5,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 175000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-01 14:41:07',
            ),
            13 => 
            array (
                'id' => 14,
                'id_member' => 3,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 175000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-13 17:28:46',
            ),
            14 => 
            array (
                'id' => 15,
                'id_member' => 2,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 175000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 18:06:18',
                'datemodified' => '2025-09-13 17:28:46',
            ),
            15 => 
            array (
                'id' => 16,
                'id_member' => 70,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-04-21 20:12:54',
            ),
            16 => 
            array (
                'id' => 17,
                'id_member' => 66,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-04-21 20:12:54',
            ),
            17 => 
            array (
                'id' => 18,
                'id_member' => 64,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 7500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-04-21 20:12:54',
            ),
            18 => 
            array (
                'id' => 19,
                'id_member' => 63,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 7500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-04-21 20:12:55',
            ),
            19 => 
            array (
                'id' => 20,
                'id_member' => 62,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 7500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-04-21 20:12:55',
            ),
            20 => 
            array (
                'id' => 21,
                'id_member' => 58,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 7500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-04-21 20:12:55',
            ),
            21 => 
            array (
                'id' => 22,
                'id_member' => 52,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 7500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-04-25 18:44:30',
            ),
            22 => 
            array (
                'id' => 23,
                'id_member' => 51,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 7500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-09-01 14:33:27',
            ),
            23 => 
            array (
                'id' => 24,
                'id_member' => 42,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 7500.0,
                'point_qualified' => 7500.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:44:34',
                'datemodified' => '2025-09-01 14:41:06',
            ),
            24 => 
            array (
                'id' => 25,
                'id_member' => 167,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 10000.0,
                'point_right' => 5000.0,
                'point_qualified' => 5000.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:45:53',
                'datemodified' => '2025-07-11 16:09:16',
            ),
            25 => 
            array (
                'id' => 26,
                'id_member' => 71,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 19:57:54',
                'datemodified' => '2025-04-21 20:12:54',
            ),
            26 => 
            array (
                'id' => 27,
                'id_member' => 169,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 20:07:24',
                'datemodified' => '2025-07-11 16:09:16',
            ),
            27 => 
            array (
                'id' => 28,
                'id_member' => 170,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-21 20:12:53',
                'datemodified' => '2025-04-22 17:20:30',
            ),
            28 => 
            array (
                'id' => 29,
                'id_member' => 90,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 10000.0,
                'point_right' => 20000.0,
                'point_qualified' => 10000.0,
                'status' => 1,
                'datecreated' => '2025-04-22 20:41:37',
                'datemodified' => '2025-06-23 18:06:30',
            ),
            29 => 
            array (
                'id' => 30,
                'id_member' => 55,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 10000.0,
                'point_right' => 30000.0,
                'point_qualified' => 10000.0,
                'status' => 1,
                'datecreated' => '2025-04-22 20:41:37',
                'datemodified' => '2025-06-22 15:21:08',
            ),
            30 => 
            array (
                'id' => 31,
                'id_member' => 54,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 40000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-22 20:41:37',
                'datemodified' => '2025-07-21 15:33:27',
            ),
            31 => 
            array (
                'id' => 32,
                'id_member' => 53,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 40000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-22 20:41:37',
                'datemodified' => '2025-07-21 15:33:27',
            ),
            32 => 
            array (
                'id' => 33,
                'id_member' => 178,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 15000.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-22 20:43:42',
                'datemodified' => '2025-06-23 18:06:30',
            ),
            33 => 
            array (
                'id' => 34,
                'id_member' => 179,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 12500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-22 20:47:11',
                'datemodified' => '2025-06-23 18:06:30',
            ),
            34 => 
            array (
                'id' => 35,
                'id_member' => 181,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-22 20:55:29',
                'datemodified' => '2025-06-23 18:06:30',
            ),
            35 => 
            array (
                'id' => 36,
                'id_member' => 28,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-23 21:00:21',
                'datemodified' => '2025-07-10 20:54:55',
            ),
            36 => 
            array (
                'id' => 37,
                'id_member' => 26,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 5000.0,
                'point_qualified' => 5000.0,
                'status' => 1,
                'datecreated' => '2025-04-23 21:00:21',
                'datemodified' => '2025-07-10 20:54:58',
            ),
            37 => 
            array (
                'id' => 38,
                'id_member' => 25,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 12500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-23 21:00:21',
                'datemodified' => '2025-08-22 14:35:18',
            ),
            38 => 
            array (
                'id' => 39,
                'id_member' => 24,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 12500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-23 21:00:21',
                'datemodified' => '2025-09-01 14:33:27',
            ),
            39 => 
            array (
                'id' => 40,
                'id_member' => 57,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-25 15:15:05',
                'datemodified' => '2025-08-24 23:24:43',
            ),
            40 => 
            array (
                'id' => 41,
                'id_member' => 56,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 5000.0,
                'point_qualified' => 5000.0,
                'status' => 1,
                'datecreated' => '2025-04-25 15:15:05',
                'datemodified' => '2025-08-22 14:42:03',
            ),
            41 => 
            array (
                'id' => 42,
                'id_member' => 41,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 12500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-25 15:15:06',
                'datemodified' => '2025-08-22 14:41:55',
            ),
            42 => 
            array (
                'id' => 43,
                'id_member' => 40,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 15000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-25 15:15:06',
                'datemodified' => '2025-08-22 14:41:55',
            ),
            43 => 
            array (
                'id' => 44,
                'id_member' => 13,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 5000.0,
                'point_qualified' => 5000.0,
                'status' => 1,
                'datecreated' => '2025-04-25 19:44:52',
                'datemodified' => '2025-06-04 16:38:00',
            ),
            44 => 
            array (
                'id' => 45,
                'id_member' => 206,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-25 19:46:44',
                'datemodified' => '2025-08-06 19:23:39',
            ),
            45 => 
            array (
                'id' => 46,
                'id_member' => 207,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-25 19:48:10',
                'datemodified' => '2025-08-06 20:48:17',
            ),
            46 => 
            array (
                'id' => 47,
                'id_member' => 209,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-25 20:19:24',
                'datemodified' => '2025-05-07 11:01:11',
            ),
            47 => 
            array (
                'id' => 48,
                'id_member' => 213,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-05-11 21:11:38',
            ),
            48 => 
            array (
                'id' => 49,
                'id_member' => 211,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-05-11 21:59:12',
            ),
            49 => 
            array (
                'id' => 50,
                'id_member' => 137,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-05-11 21:59:12',
            ),
            50 => 
            array (
                'id' => 51,
                'id_member' => 135,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-05-11 21:59:12',
            ),
            51 => 
            array (
                'id' => 52,
                'id_member' => 113,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-05-11 21:58:28',
            ),
            52 => 
            array (
                'id' => 53,
                'id_member' => 112,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-06-11 14:19:27',
            ),
            53 => 
            array (
                'id' => 54,
                'id_member' => 111,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-06-11 14:19:27',
            ),
            54 => 
            array (
                'id' => 55,
                'id_member' => 109,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-06-26 12:51:59',
            ),
            55 => 
            array (
                'id' => 56,
                'id_member' => 107,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 5000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-06-26 12:54:58',
            ),
            56 => 
            array (
                'id' => 57,
                'id_member' => 106,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 20000.0,
                'point_right' => 5000.0,
                'point_qualified' => 5000.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-06-26 12:58:03',
            ),
            57 => 
            array (
                'id' => 58,
                'id_member' => 15,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 25000.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-06-26 13:08:07',
            ),
            58 => 
            array (
                'id' => 59,
                'id_member' => 11,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 27500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-27 12:27:29',
                'datemodified' => '2025-06-26 12:58:03',
            ),
            59 => 
            array (
                'id' => 60,
                'id_member' => 180,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 10000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-29 16:58:44',
                'datemodified' => '2025-06-22 09:53:45',
            ),
            60 => 
            array (
                'id' => 61,
                'id_member' => 221,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 5000.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-04-29 17:08:02',
                'datemodified' => '2025-06-22 09:53:45',
            ),
            61 => 
            array (
                'id' => 62,
                'id_member' => 33,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-01 14:28:55',
                'datemodified' => '2025-06-23 08:31:34',
            ),
            62 => 
            array (
                'id' => 63,
                'id_member' => 32,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-01 14:28:55',
                'datemodified' => '2025-06-23 08:31:34',
            ),
            63 => 
            array (
                'id' => 64,
                'id_member' => 30,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-01 14:28:55',
                'datemodified' => '2025-06-23 08:31:34',
            ),
            64 => 
            array (
                'id' => 65,
                'id_member' => 224,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-01 20:30:37',
                'datemodified' => '2025-06-22 15:17:10',
            ),
            65 => 
            array (
                'id' => 66,
                'id_member' => 225,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-01 21:40:56',
                'datemodified' => '2025-05-17 08:53:09',
            ),
            66 => 
            array (
                'id' => 67,
                'id_member' => 151,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-05 17:38:42',
                'datemodified' => '2025-06-26 12:54:58',
            ),
            67 => 
            array (
                'id' => 68,
                'id_member' => 149,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-05 17:38:42',
                'datemodified' => '2025-06-26 12:54:58',
            ),
            68 => 
            array (
                'id' => 69,
                'id_member' => 215,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-05 18:09:41',
                'datemodified' => '2025-05-05 18:09:45',
            ),
            69 => 
            array (
                'id' => 70,
                'id_member' => 214,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-05 18:09:41',
                'datemodified' => '2025-05-05 18:09:41',
            ),
            70 => 
            array (
                'id' => 71,
                'id_member' => 226,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-06 23:48:16',
                'datemodified' => '2025-05-17 08:53:09',
            ),
            71 => 
            array (
                'id' => 72,
                'id_member' => 171,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-05-07 21:07:57',
                'datemodified' => '2025-07-11 16:09:16',
            ),
            72 => 
            array (
                'id' => 73,
                'id_member' => 36,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-05-15 19:08:41',
                'datemodified' => '2025-06-23 08:30:46',
            ),
            73 => 
            array (
                'id' => 74,
                'id_member' => 35,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-15 19:08:41',
                'datemodified' => '2025-06-23 08:31:22',
            ),
            74 => 
            array (
                'id' => 75,
                'id_member' => 27,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-15 19:08:41',
                'datemodified' => '2025-07-10 20:54:55',
            ),
            75 => 
            array (
                'id' => 76,
                'id_member' => 184,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-18 13:27:17',
                'datemodified' => '2025-07-11 16:09:16',
            ),
            76 => 
            array (
                'id' => 77,
                'id_member' => 182,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-24 21:20:19',
                'datemodified' => '2025-06-23 18:06:30',
            ),
            77 => 
            array (
                'id' => 78,
                'id_member' => 240,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-27 22:05:15',
                'datemodified' => '2025-08-22 14:42:03',
            ),
            78 => 
            array (
                'id' => 79,
                'id_member' => 75,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-29 12:57:37',
                'datemodified' => '2025-06-23 08:30:26',
            ),
            79 => 
            array (
                'id' => 80,
                'id_member' => 61,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-29 12:57:37',
                'datemodified' => '2025-06-23 08:30:31',
            ),
            80 => 
            array (
                'id' => 81,
                'id_member' => 37,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-29 12:57:37',
                'datemodified' => '2025-06-23 08:30:36',
            ),
            81 => 
            array (
                'id' => 82,
                'id_member' => 245,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-29 19:49:19',
                'datemodified' => '2025-06-23 08:30:22',
            ),
            82 => 
            array (
                'id' => 83,
                'id_member' => 227,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-03 23:12:32',
                'datemodified' => '2025-06-22 09:53:43',
            ),
            83 => 
            array (
                'id' => 84,
                'id_member' => 125,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 12:36:36',
                'datemodified' => '2025-06-04 12:36:41',
            ),
            84 => 
            array (
                'id' => 85,
                'id_member' => 124,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 12:36:36',
                'datemodified' => '2025-06-04 12:36:36',
            ),
            85 => 
            array (
                'id' => 86,
                'id_member' => 122,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 12:36:36',
                'datemodified' => '2025-06-11 14:16:40',
            ),
            86 => 
            array (
                'id' => 87,
                'id_member' => 121,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 12:36:36',
                'datemodified' => '2025-06-26 12:51:59',
            ),
            87 => 
            array (
                'id' => 88,
                'id_member' => 108,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 17500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-06-04 12:36:36',
                'datemodified' => '2025-06-26 12:58:03',
            ),
            88 => 
            array (
                'id' => 89,
                'id_member' => 237,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 10000.0,
                'point_right' => 10000.0,
                'point_qualified' => 10000.0,
                'status' => 1,
                'datecreated' => '2025-06-04 16:55:46',
                'datemodified' => '2025-08-15 11:58:56',
            ),
            89 => 
            array (
                'id' => 90,
                'id_member' => 176,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 20000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 16:55:46',
                'datemodified' => '2025-08-15 11:58:56',
            ),
            90 => 
            array (
                'id' => 91,
                'id_member' => 19,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 20000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 16:55:46',
                'datemodified' => '2025-08-15 11:58:57',
            ),
            91 => 
            array (
                'id' => 92,
                'id_member' => 251,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 16:57:58',
                'datemodified' => '2025-08-15 11:56:20',
            ),
            92 => 
            array (
                'id' => 93,
                'id_member' => 253,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 7500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 17:04:05',
                'datemodified' => '2025-08-15 11:58:56',
            ),
            93 => 
            array (
                'id' => 94,
                'id_member' => 228,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-07 11:54:27',
                'datemodified' => '2025-06-07 11:54:31',
            ),
            94 => 
            array (
                'id' => 95,
                'id_member' => 194,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-07 11:54:27',
                'datemodified' => '2025-06-07 11:54:27',
            ),
            95 => 
            array (
                'id' => 96,
                'id_member' => 193,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-07 11:54:27',
                'datemodified' => '2025-06-07 11:54:27',
            ),
            96 => 
            array (
                'id' => 97,
                'id_member' => 191,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-07 11:54:27',
                'datemodified' => '2025-06-07 11:54:27',
            ),
            97 => 
            array (
                'id' => 98,
                'id_member' => 190,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-07 11:54:27',
                'datemodified' => '2025-06-07 11:54:27',
            ),
            98 => 
            array (
                'id' => 99,
                'id_member' => 186,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-07 11:54:27',
                'datemodified' => '2025-06-07 11:54:27',
            ),
            99 => 
            array (
                'id' => 100,
                'id_member' => 14,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-07 11:54:27',
                'datemodified' => '2025-06-07 11:54:31',
            ),
            100 => 
            array (
                'id' => 101,
                'id_member' => 120,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-11 14:05:36',
                'datemodified' => '2025-06-11 14:05:42',
            ),
            101 => 
            array (
                'id' => 102,
                'id_member' => 119,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-11 14:05:36',
                'datemodified' => '2025-06-11 14:05:36',
            ),
            102 => 
            array (
                'id' => 103,
                'id_member' => 117,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-11 14:05:36',
                'datemodified' => '2025-06-11 14:05:36',
            ),
            103 => 
            array (
                'id' => 104,
                'id_member' => 115,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-11 14:05:36',
                'datemodified' => '2025-06-11 14:19:27',
            ),
            104 => 
            array (
                'id' => 105,
                'id_member' => 110,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-11 14:05:36',
                'datemodified' => '2025-06-11 14:19:27',
            ),
            105 => 
            array (
                'id' => 106,
                'id_member' => 257,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 15000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-11 14:48:06',
                'datemodified' => '2025-06-26 12:58:03',
            ),
            106 => 
            array (
                'id' => 107,
                'id_member' => 258,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 7500.0,
                'point_right' => 5000.0,
                'point_qualified' => 5000.0,
                'status' => 1,
                'datecreated' => '2025-06-11 14:57:48',
                'datemodified' => '2025-06-26 12:58:02',
            ),
            107 => 
            array (
                'id' => 108,
                'id_member' => 259,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-11 16:04:53',
                'datemodified' => '2025-06-26 12:56:26',
            ),
            108 => 
            array (
                'id' => 109,
                'id_member' => 229,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 7500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-11 19:34:21',
                'datemodified' => '2025-07-11 16:00:20',
            ),
            109 => 
            array (
                'id' => 110,
                'id_member' => 79,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-12 20:40:12',
                'datemodified' => '2025-07-21 15:40:01',
            ),
            110 => 
            array (
                'id' => 111,
                'id_member' => 77,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-12 20:40:12',
                'datemodified' => '2025-07-21 15:40:01',
            ),
            111 => 
            array (
                'id' => 112,
                'id_member' => 76,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-12 20:40:12',
                'datemodified' => '2025-09-01 13:32:27',
            ),
            112 => 
            array (
                'id' => 113,
                'id_member' => 46,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-06-12 20:40:12',
                'datemodified' => '2025-09-01 14:25:39',
            ),
            113 => 
            array (
                'id' => 114,
                'id_member' => 45,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-12 20:40:12',
                'datemodified' => '2025-09-01 14:25:39',
            ),
            114 => 
            array (
                'id' => 115,
                'id_member' => 44,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-06-12 20:40:12',
                'datemodified' => '2025-09-01 14:41:06',
            ),
            115 => 
            array (
                'id' => 116,
                'id_member' => 252,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-13 16:07:35',
                'datemodified' => '2025-08-15 11:56:20',
            ),
            116 => 
            array (
                'id' => 117,
                'id_member' => 244,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-18 23:42:14',
                'datemodified' => '2025-08-22 14:42:03',
            ),
            117 => 
            array (
                'id' => 118,
                'id_member' => 262,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-06-20 22:15:30',
                'datemodified' => '2025-07-11 16:00:20',
            ),
            118 => 
            array (
                'id' => 119,
                'id_member' => 243,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-22 15:21:07',
                'datemodified' => '2025-06-23 18:06:14',
            ),
            119 => 
            array (
                'id' => 120,
                'id_member' => 261,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 5000.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-26 12:56:22',
                'datemodified' => '2025-06-26 12:58:02',
            ),
            120 => 
            array (
                'id' => 121,
                'id_member' => 269,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-26 12:58:02',
                'datemodified' => '2025-06-26 13:08:07',
            ),
            121 => 
            array (
                'id' => 122,
                'id_member' => 166,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-07-10 21:04:06',
                'datemodified' => '2025-07-12 23:15:50',
            ),
            122 => 
            array (
                'id' => 123,
                'id_member' => 60,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-07-10 21:04:06',
                'datemodified' => '2025-08-22 14:35:18',
            ),
            123 => 
            array (
                'id' => 124,
                'id_member' => 254,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 5000.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-07-15 10:26:03',
                'datemodified' => '2025-08-15 11:58:56',
            ),
            124 => 
            array (
                'id' => 125,
                'id_member' => 274,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 2500.0,
                'point_qualified' => 2500.0,
                'status' => 1,
                'datecreated' => '2025-07-21 23:25:09',
                'datemodified' => '2025-09-13 17:28:46',
            ),
            125 => 
            array (
                'id' => 126,
                'id_member' => 264,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-08-15 11:55:31',
                'datemodified' => '2025-08-15 11:55:39',
            ),
            126 => 
            array (
                'id' => 127,
                'id_member' => 273,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-08-15 11:58:56',
                'datemodified' => '2025-08-15 11:59:01',
            ),
            127 => 
            array (
                'id' => 128,
                'id_member' => 48,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-09-01 14:25:38',
                'datemodified' => '2025-09-01 14:26:03',
            ),
            128 => 
            array (
                'id' => 129,
                'id_member' => 47,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-09-01 14:25:38',
                'datemodified' => '2025-09-01 14:25:39',
            ),
            129 => 
            array (
                'id' => 130,
                'id_member' => 94,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-09-01 14:41:06',
                'datemodified' => '2025-09-01 14:41:06',
            ),
            130 => 
            array (
                'id' => 131,
                'id_member' => 93,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 2500.0,
                'point_right' => 0.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-09-01 14:41:06',
                'datemodified' => '2025-09-01 14:41:06',
            ),
            131 => 
            array (
                'id' => 132,
                'id_member' => 49,
                'type' => 'pairing',
                'period' => 0,
                'period_start' => NULL,
                'period_end' => NULL,
                'point_left' => 0.0,
                'point_right' => 2500.0,
                'point_qualified' => 0.0,
                'status' => 1,
                'datecreated' => '2025-09-01 14:41:06',
                'datemodified' => '2025-09-01 14:41:06',
            ),
        ));
        
        
    }
}