<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JpbProductStockOutTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('product_stock_outs')->delete();

        \DB::table('product_stock_outs')->insert([
            0 => [
                'id' => 1,
                'id_warehouse' => 0,
                'id_member' => 2,
                'id_source' => 1,
                'source' => 'shop',
                'id_detail' => 1,
                'product' => 1,
                'varian' => 0,
                'qty' => 3,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000229',
                'datecreated' => '2025-04-21 13:40:24',
            ],
            1 => [
                'id' => 2,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 2,
                'source' => 'shop',
                'id_detail' => 2,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000230',
                'datecreated' => '2025-04-21 17:50:58',
            ],
            2 => [
                'id' => 3,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 3,
                'source' => 'shop',
                'id_detail' => 3,
                'product' => 1,
                'varian' => 0,
                'qty' => 2,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000231',
                'datecreated' => '2025-04-21 18:40:51',
            ],
            3 => [
                'id' => 4,
                'id_warehouse' => 0,
                'id_member' => 22,
                'id_source' => 4,
                'source' => 'shop',
                'id_detail' => 4,
                'product' => 1,
                'varian' => 0,
                'qty' => 3,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000232',
                'datecreated' => '2025-04-21 18:43:02',
            ],
            4 => [
                'id' => 5,
                'id_warehouse' => 0,
                'id_member' => 17,
                'id_source' => 5,
                'source' => 'shop',
                'id_detail' => 5,
                'product' => 1,
                'varian' => 0,
                'qty' => 5,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000233',
                'datecreated' => '2025-04-22 19:13:52',
            ],
            5 => [
                'id' => 6,
                'id_warehouse' => 0,
                'id_member' => 26,
                'id_source' => 6,
                'source' => 'shop',
                'id_detail' => 6,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000234',
                'datecreated' => '2025-04-23 18:54:46',
            ],
            6 => [
                'id' => 7,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 7,
                'source' => 'shop',
                'id_detail' => 7,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000235',
                'datecreated' => '2025-04-24 20:03:06',
            ],
            7 => [
                'id' => 8,
                'id_warehouse' => 0,
                'id_member' => 35,
                'id_source' => 8,
                'source' => 'shop',
                'id_detail' => 8,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000236',
                'datecreated' => '2025-04-25 10:30:55',
            ],
            8 => [
                'id' => 9,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 9,
                'source' => 'shop',
                'id_detail' => 9,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000237',
                'datecreated' => '2025-04-25 14:18:08',
            ],
            9 => [
                'id' => 10,
                'id_warehouse' => 0,
                'id_member' => 17,
                'id_source' => 10,
                'source' => 'shop',
                'id_detail' => 10,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000238',
                'datecreated' => '2025-04-25 19:32:42',
            ],
            10 => [
                'id' => 11,
                'id_warehouse' => 0,
                'id_member' => 13,
                'id_source' => 11,
                'source' => 'shop',
                'id_detail' => 11,
                'product' => 1,
                'varian' => 0,
                'qty' => 4,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000239',
                'datecreated' => '2025-04-25 19:42:44',
            ],
            11 => [
                'id' => 12,
                'id_warehouse' => 0,
                'id_member' => 15,
                'id_source' => 12,
                'source' => 'shop',
                'id_detail' => 12,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000240',
                'datecreated' => '2025-04-27 12:22:12',
            ],
            12 => [
                'id' => 13,
                'id_warehouse' => 0,
                'id_member' => 21,
                'id_source' => 13,
                'source' => 'shop',
                'id_detail' => 13,
                'product' => 1,
                'varian' => 0,
                'qty' => 2,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000241',
                'datecreated' => '2025-04-29 16:20:17',
            ],
            13 => [
                'id' => 14,
                'id_warehouse' => 0,
                'id_member' => 21,
                'id_source' => 14,
                'source' => 'shop',
                'id_detail' => 14,
                'product' => 1,
                'varian' => 0,
                'qty' => 2,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000242',
                'datecreated' => '2025-04-30 12:08:18',
            ],
            14 => [
                'id' => 15,
                'id_warehouse' => 0,
                'id_member' => 26,
                'id_source' => 15,
                'source' => 'shop',
                'id_detail' => 15,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000243',
                'datecreated' => '2025-05-01 13:51:38',
            ],
            15 => [
                'id' => 16,
                'id_warehouse' => 0,
                'id_member' => 21,
                'id_source' => 16,
                'source' => 'shop',
                'id_detail' => 16,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000244',
                'datecreated' => '2025-05-01 21:27:06',
            ],
            16 => [
                'id' => 17,
                'id_warehouse' => 0,
                'id_member' => 21,
                'id_source' => 17,
                'source' => 'shop',
                'id_detail' => 17,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000245',
                'datecreated' => '2025-05-02 11:33:28',
            ],
            17 => [
                'id' => 18,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 18,
                'source' => 'shop',
                'id_detail' => 18,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000246',
                'datecreated' => '2025-05-04 09:10:24',
            ],
            18 => [
                'id' => 19,
                'id_warehouse' => 0,
                'id_member' => 15,
                'id_source' => 19,
                'source' => 'shop',
                'id_detail' => 19,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000247',
                'datecreated' => '2025-05-05 17:26:30',
            ],
            19 => [
                'id' => 20,
                'id_warehouse' => 0,
                'id_member' => 13,
                'id_source' => 20,
                'source' => 'shop',
                'id_detail' => 20,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000248',
                'datecreated' => '2025-05-05 18:07:33',
            ],
            20 => [
                'id' => 21,
                'id_warehouse' => 0,
                'id_member' => 21,
                'id_source' => 21,
                'source' => 'shop',
                'id_detail' => 21,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000249',
                'datecreated' => '2025-05-06 15:20:40',
            ],
            21 => [
                'id' => 22,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 22,
                'source' => 'shop',
                'id_detail' => 22,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000250',
                'datecreated' => '2025-05-07 19:09:59',
            ],
            22 => [
                'id' => 23,
                'id_warehouse' => 0,
                'id_member' => 35,
                'id_source' => 23,
                'source' => 'shop',
                'id_detail' => 23,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000251',
                'datecreated' => '2025-05-14 11:04:13',
            ],
            23 => [
                'id' => 24,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 24,
                'source' => 'shop',
                'id_detail' => 24,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000252',
                'datecreated' => '2025-05-16 06:41:16',
            ],
            24 => [
                'id' => 25,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 25,
                'source' => 'shop',
                'id_detail' => 25,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000253',
                'datecreated' => '2025-05-18 12:56:57',
            ],
            25 => [
                'id' => 26,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 26,
                'source' => 'shop',
                'id_detail' => 26,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000254',
                'datecreated' => '2025-05-20 14:33:23',
            ],
            26 => [
                'id' => 27,
                'id_warehouse' => 0,
                'id_member' => 21,
                'id_source' => 27,
                'source' => 'shop',
                'id_detail' => 27,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000255',
                'datecreated' => '2025-05-22 13:39:02',
            ],
            27 => [
                'id' => 28,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 28,
                'source' => 'shop',
                'id_detail' => 28,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000256',
                'datecreated' => '2025-05-27 20:37:39',
            ],
            28 => [
                'id' => 29,
                'id_warehouse' => 0,
                'id_member' => 35,
                'id_source' => 29,
                'source' => 'shop',
                'id_detail' => 29,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000257',
                'datecreated' => '2025-05-29 14:45:27',
            ],
            29 => [
                'id' => 30,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 30,
                'source' => 'shop',
                'id_detail' => 30,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000258',
                'datecreated' => '2025-05-29 19:25:04',
            ],
            30 => [
                'id' => 31,
                'id_warehouse' => 0,
                'id_member' => 22,
                'id_source' => 31,
                'source' => 'shop',
                'id_detail' => 31,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000259',
                'datecreated' => '2025-05-30 13:14:59',
            ],
            31 => [
                'id' => 32,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 32,
                'source' => 'shop',
                'id_detail' => 32,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000260',
                'datecreated' => '2025-05-30 17:02:39',
            ],
            32 => [
                'id' => 33,
                'id_warehouse' => 0,
                'id_member' => 15,
                'id_source' => 33,
                'source' => 'shop',
                'id_detail' => 33,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000261',
                'datecreated' => '2025-05-31 15:10:41',
            ],
            33 => [
                'id' => 34,
                'id_warehouse' => 0,
                'id_member' => 21,
                'id_source' => 34,
                'source' => 'shop',
                'id_detail' => 34,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000262',
                'datecreated' => '2025-06-03 21:21:24',
            ],
            34 => [
                'id' => 35,
                'id_warehouse' => 0,
                'id_member' => 17,
                'id_source' => 35,
                'source' => 'shop',
                'id_detail' => 35,
                'product' => 1,
                'varian' => 0,
                'qty' => 4,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000263',
                'datecreated' => '2025-06-04 16:45:38',
            ],
            35 => [
                'id' => 36,
                'id_warehouse' => 0,
                'id_member' => 15,
                'id_source' => 36,
                'source' => 'shop',
                'id_detail' => 36,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000264',
                'datecreated' => '2025-06-11 14:01:13',
            ],
            36 => [
                'id' => 37,
                'id_warehouse' => 0,
                'id_member' => 15,
                'id_source' => 37,
                'source' => 'shop',
                'id_detail' => 37,
                'product' => 1,
                'varian' => 0,
                'qty' => 5,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000265',
                'datecreated' => '2025-06-11 14:18:43',
            ],
            37 => [
                'id' => 38,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 38,
                'source' => 'shop',
                'id_detail' => 38,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000266',
                'datecreated' => '2025-06-11 18:22:22',
            ],
            38 => [
                'id' => 39,
                'id_warehouse' => 0,
                'id_member' => 17,
                'id_source' => 39,
                'source' => 'shop',
                'id_detail' => 39,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000267',
                'datecreated' => '2025-06-13 16:02:13',
            ],
            39 => [
                'id' => 40,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 40,
                'source' => 'shop',
                'id_detail' => 40,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000268',
                'datecreated' => '2025-06-18 21:06:32',
            ],
            40 => [
                'id' => 41,
                'id_warehouse' => 0,
                'id_member' => 21,
                'id_source' => 41,
                'source' => 'shop',
                'id_detail' => 41,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000269',
                'datecreated' => '2025-06-20 09:25:41',
            ],
            41 => [
                'id' => 42,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 42,
                'source' => 'shop',
                'id_detail' => 42,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000270',
                'datecreated' => '2025-06-20 20:06:01',
            ],
            42 => [
                'id' => 43,
                'id_warehouse' => 0,
                'id_member' => 15,
                'id_source' => 43,
                'source' => 'shop',
                'id_detail' => 43,
                'product' => 1,
                'varian' => 0,
                'qty' => 2,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000271',
                'datecreated' => '2025-06-26 12:53:16',
            ],
            43 => [
                'id' => 44,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 44,
                'source' => 'shop',
                'id_detail' => 44,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000272',
                'datecreated' => '2025-06-26 20:07:11',
            ],
            44 => [
                'id' => 45,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 45,
                'source' => 'shop',
                'id_detail' => 45,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000273',
                'datecreated' => '2025-07-10 20:49:23',
            ],
            45 => [
                'id' => 46,
                'id_warehouse' => 0,
                'id_member' => 17,
                'id_source' => 46,
                'source' => 'shop',
                'id_detail' => 46,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000274',
                'datecreated' => '2025-07-14 16:03:27',
            ],
            46 => [
                'id' => 47,
                'id_warehouse' => 0,
                'id_member' => 275,
                'id_source' => 49,
                'source' => 'shop',
                'id_detail' => 49,
                'product' => 3,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000276',
                'datecreated' => '2025-07-21 23:25:09',
            ],
            47 => [
                'id' => 48,
                'id_warehouse' => 0,
                'id_member' => 276,
                'id_source' => 50,
                'source' => 'shop',
                'id_detail' => 50,
                'product' => 4,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000277',
                'datecreated' => '2025-07-21 23:25:18',
            ],
            48 => [
                'id' => 49,
                'id_warehouse' => 0,
                'id_member' => 23,
                'id_source' => 51,
                'source' => 'shop',
                'id_detail' => 51,
                'product' => 1,
                'varian' => 0,
                'qty' => 1,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000278',
                'datecreated' => '2025-08-01 12:01:45',
            ],
            49 => [
                'id' => 50,
                'id_warehouse' => 0,
                'id_member' => 17,
                'id_source' => 53,
                'source' => 'shop',
                'id_detail' => 53,
                'product' => 1,
                'varian' => 0,
                'qty' => 2,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000280',
                'datecreated' => '2025-08-15 11:35:48',
            ],
            50 => [
                'id' => 51,
                'id_warehouse' => 0,
                'id_member' => 22,
                'id_source' => 54,
                'source' => 'shop',
                'id_detail' => 54,
                'product' => 1,
                'varian' => 0,
                'qty' => 2,
                'status' => 1,
                'description' => 'Stok Keluar dari Pesanan #INV/00000281',
                'datecreated' => '2025-08-28 15:42:37',
            ],
        ]);

    }
}
