<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class JpbRanksTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('jpb_ranks')->delete();

        \DB::table('jpb_ranks')->insert([
            0 => [
                'id' => 1,
                'id_member' => 2,
                'username' => 'jpbuana',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 7,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            1 => [
                'id' => 2,
                'id_member' => 9,
                'username' => 'jpbasil',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 11,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            2 => [
                'id' => 3,
                'id_member' => 17,
                'username' => 'mastermanifestasi',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            3 => [
                'id' => 4,
                'id_member' => 18,
                'username' => 'align',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            4 => [
                'id' => 5,
                'id_member' => 19,
                'username' => 'joyandglory',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            5 => [
                'id' => 6,
                'id_member' => 21,
                'username' => 'moneymagnet',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 7,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            6 => [
                'id' => 7,
                'id_member' => 23,
                'username' => 'eternalglory',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 6,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            7 => [
                'id' => 8,
                'id_member' => 26,
                'username' => 'founderjpb',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            8 => [
                'id' => 9,
                'id_member' => 42,
                'username' => 'joel225',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 5,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            9 => [
                'id' => 10,
                'id_member' => 44,
                'username' => 'cikaya',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            10 => [
                'id' => 11,
                'id_member' => 58,
                'username' => 'cakra69',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            11 => [
                'id' => 12,
                'id_member' => 82,
                'username' => 'cakrasani',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            12 => [
                'id' => 13,
                'id_member' => 93,
                'username' => 'figoalamo',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 10,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            13 => [
                'id' => 14,
                'id_member' => 106,
                'username' => 'diandomenie',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 9,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            14 => [
                'id' => 15,
                'id_member' => 109,
                'username' => 'infinity',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 6,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            15 => [
                'id' => 16,
                'id_member' => 121,
                'username' => 'ningsih',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 6,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            16 => [
                'id' => 17,
                'id_member' => 135,
                'username' => 'jpb001',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 4,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            17 => [
                'id' => 18,
                'id_member' => 139,
                'username' => 'oscar168',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 8,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            18 => [
                'id' => 19,
                'id_member' => 149,
                'username' => 'donwoge',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            19 => [
                'id' => 20,
                'id_member' => 152,
                'username' => 'arpannora',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 4,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:04:27',
                'datemodified' => '2025-04-24 16:04:27',
            ],
            20 => [
                'id' => 21,
                'id_member' => 64,
                'username' => 'legendai',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:09:50',
                'datemodified' => '2025-04-24 16:09:50',
            ],
            21 => [
                'id' => 22,
                'id_member' => 76,
                'username' => 'MARITACHAMPION',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-24 16:10:38',
                'datemodified' => '2025-04-24 16:10:38',
            ],
            22 => [
                'id' => 23,
                'id_member' => 14,
                'username' => 'jpbasil6',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-25 17:43:51',
                'datemodified' => '2025-04-25 17:43:51',
            ],
            23 => [
                'id' => 24,
                'id_member' => 13,
                'username' => 'jpbasil5',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 4,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-25 20:10:06',
                'datemodified' => '2025-04-25 20:10:06',
            ],
            24 => [
                'id' => 25,
                'id_member' => 38,
                'username' => 'cakrawala369',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-25 21:18:59',
                'datemodified' => '2025-04-25 21:18:59',
            ],
            25 => [
                'id' => 26,
                'id_member' => 167,
                'username' => 'queenla',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-25 21:20:43',
                'datemodified' => '2025-04-25 21:20:43',
            ],
            26 => [
                'id' => 27,
                'id_member' => 12,
                'username' => 'jpbasil4',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-04-26 18:59:01',
                'datemodified' => '2025-04-26 18:59:01',
            ],
            27 => [
                'id' => 28,
                'id_member' => 32,
                'username' => 'myhandoyo',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-01 23:23:00',
                'datemodified' => '2025-05-01 23:23:00',
            ],
            28 => [
                'id' => 29,
                'id_member' => 186,
                'username' => 'sarah',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-04 11:13:57',
                'datemodified' => '2025-05-04 11:13:57',
            ],
            29 => [
                'id' => 30,
                'id_member' => 39,
                'username' => 'chakrabuana369',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-05-07 23:23:00',
                'datemodified' => '2025-05-07 23:23:00',
            ],
            30 => [
                'id' => 31,
                'id_member' => 237,
                'username' => 'shin10',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-04 17:04:05',
                'datemodified' => '2025-06-04 17:04:05',
            ],
            31 => [
                'id' => 32,
                'id_member' => 258,
                'username' => 'wiwinkunarti',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-06-26 12:58:02',
                'datemodified' => '2025-06-26 12:58:02',
            ],
            32 => [
                'id' => 33,
                'id_member' => 22,
                'username' => 'mostwanted',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-09-01 14:41:05',
                'datemodified' => '2025-09-01 14:41:05',
            ],
            33 => [
                'id' => 34,
                'id_member' => 274,
                'username' => 'demoaccount',
                'rank' => 'star',
                'rank_index' => 2,
                'downline' => 3,
                'point_left' => 0.0,
                'point_right' => 0.0,
                'status' => 1,
                'datecreated' => '2025-09-09 15:29:13',
                'datemodified' => '2025-09-09 15:29:13',
            ],
        ]);

    }
}
